
// 默认报告配置用假数据
const mockReportData = [
  {
    processId: 'b1f4360f041646959a3339782826e038',
    deptCode: '001',
    deptId: 'e5dd96ad4e104fbe8500d02c2ae71207',
    deptName: '市妇幼保健中心',
    activityName: '活动名称',
    programCode: '0102',
    batchNum: '1',
    responsibleDepartment: '负责科室',
    roomplanYear: '2023',
    contact: 1123353444,
    labDate: '2023-02-14',
    reportDate: '2023-04-11 00:00:00',
    totalScore: '100.0%',
    reportDetailList: [
      {
        itemId: '8',
        itemName: 'AFP',
        score: '100.0%',
        calculateGroupName: '',
        groupLabNum: '1',
        unit: '',
        method: null,
        inName: 'AutoDELFIA',
        reagent: '12',
        standard: '123',
        roomResultList: [
          {
            roomDataLevel: '202311',
            roomResult: 2,
            roomX: 2,
            roomSd: 0,
            offset: '0.0',
            nsd: 0,
            range: '1.4~2.6',
            evaluateResult: '通过'
          },
          {
            roomDataLevel: '202312',
            roomResult: 2,
            roomX: 2,
            roomSd: 0,
            offset: '0.0',
            nsd: 0,
            range: '1.4~2.6',
            evaluateResult: '通过'
          },
          {
            roomDataLevel: '202313',
            roomResult: 2,
            roomX: 2,
            roomSd: 0,
            offset: '0.0',
            nsd: 0,
            range: '1.4~2.6',
            evaluateResult: '通过'
          },
          {
            roomDataLevel: '202314',
            roomResult: 2,
            roomX: 2,
            roomSd: 0,
            offset: '0.0',
            nsd: 0,
            range: '1.4~2.6',
            evaluateResult: '通过'
          },
          {
            roomDataLevel: '202315',
            roomResult: 2,
            roomX: 2,
            roomSd: 0,
            offset: '0.0',
            nsd: 0,
            range: '1.4~2.6',
            evaluateResult: '通过'
          }
        ],
        planStatisticsDtoList: null,
        projectName: 'AFP-HCG(中)',
        projectId: 1
      },
      {
        itemId: '68',
        itemName: 'CMA',
        score: null,
        calculateGroupName: null,
        groupLabNum: null,
        unit: null,
        method: null,
        instrumentName: null,
        instrumentType: null,
        reagentType: null,
        reagentNum: null,
        reagent: null,
        standard: null,
        itemQualityResultStatisticalMethod: 0,
        roomResultList: null,
        planStatisticsDtoList: null,
        describeList: [
          {
            processId: 'e4f388f5375041eeb27f35bcc5847010',
            deptCode: null,
            deptId: '4ff6b32fc34d4a849a6ba1b96b7bd385',
            deptName: null,
            activityName: null,
            programCode: null,
            batchNum: '5',
            responsibleDepartment: null,
            contact: null,
            labDate: '2024-03-27',
            reportDate: '2024-03-27 00:00:00',
            totalScore: null,
            roomDataLevel: '202411',
            roomDescribe: '12',
            expectedValue: null,
            remark: '90',
            status: 1,
            targetId: '68',
            targetName: 'CMA',
            fileName: '333.pdf',
            filePath: 'https://oss1.biosan.cn/datacenter/heart/333-rc-upload-1711505207971-11.pdf'
          },
          {
            processId: 'e4f388f5375041eeb27f35bcc5847010',
            deptCode: null,
            deptId: '4ff6b32fc34d4a849a6ba1b96b7bd385',
            deptName: null,
            activityName: null,
            programCode: null,
            batchNum: '5',
            responsibleDepartment: null,
            contact: null,
            labDate: '2024-03-27',
            reportDate: '2024-03-27 00:00:00',
            totalScore: null,
            roomDataLevel: '202412',
            roomDescribe: '34',
            expectedValue: null,
            remark: '20',
            status: 1,
            targetId: '68',
            targetName: 'CMA',
            fileName: 'The Loneliest Girl.pdf',
            filePath: 'https://oss1.biosan.cn/datacenter/heart/The Loneliest Girl-rc-upload-1711505207971-13.pdf'
          },
          {
            processId: 'e4f388f5375041eeb27f35bcc5847010',
            deptCode: null,
            deptId: '4ff6b32fc34d4a849a6ba1b96b7bd385',
            deptName: null,
            activityName: null,
            programCode: null,
            batchNum: '5',
            responsibleDepartment: null,
            contact: null,
            labDate: '2024-03-27',
            reportDate: '2024-03-27 00:00:00',
            totalScore: null,
            roomDataLevel: '202413',
            roomDescribe: '56',
            expectedValue: null,
            remark: '60',
            status: -1,
            targetId: '68',
            targetName: 'CMA',
            fileName: '9d420b57-42ae-4f5e-bdce-77647d5a8981.jpeg',
            filePath: 'https://oss1.biosan.cn/datacenter/heart/9d420b57-42ae-4f5e-bdce-77647d5a8981-rc-upload-1711505207971-15.jpeg'
          },
          {
            processId: 'e4f388f5375041eeb27f35bcc5847010',
            deptCode: null,
            deptId: '4ff6b32fc34d4a849a6ba1b96b7bd385',
            deptName: null,
            activityName: null,
            programCode: null,
            batchNum: '5',
            responsibleDepartment: null,
            contact: null,
            labDate: '2024-03-27',
            reportDate: '2024-03-27 00:00:00',
            totalScore: null,
            roomDataLevel: '202414',
            roomDescribe: '78',
            expectedValue: null,
            remark: '30',
            status: -1,
            targetId: '68',
            targetName: 'CMA',
            fileName: 'x.png',
            filePath: 'https://oss1.biosan.cn/datacenter/heart/x-rc-upload-1711505207971-17.png'
          },
          {
            processId: 'e4f388f5375041eeb27f35bcc5847010',
            deptCode: null,
            deptId: '4ff6b32fc34d4a849a6ba1b96b7bd385',
            deptName: null,
            activityName: null,
            programCode: null,
            batchNum: '5',
            responsibleDepartment: null,
            contact: null,
            labDate: '2024-03-27',
            reportDate: '2024-03-27 00:00:00',
            totalScore: null,
            roomDataLevel: '202415',
            roomDescribe: '90',
            expectedValue: null,
            remark: '100',
            status: -1,
            targetId: '68',
            targetName: 'CMA',
            fileName: '1624932773714.jpg',
            filePath: 'https://oss1.biosan.cn/datacenter/heart/1624932773714-rc-upload-1711505207971-19.jpg'
          }
        ],
        dataAttachmentsList: [
          {
            readId: null,
            dataId: null,
            status: 1,
            remark: '90',
            level: '202411',
            result: '333.pdf',
            itemName: 'CMA',
            itemId: 68,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: 1,
            remark: '20',
            level: '202412',
            result: 'The Loneliest Girl.pdf',
            itemName: 'CMA',
            itemId: 68,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: -1,
            remark: '60',
            level: '202413',
            result: '9d420b57-42ae-4f5e-bdce-77647d5a8981.jpeg',
            itemName: 'CMA',
            itemId: 68,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: -1,
            remark: '30',
            level: '202414',
            result: 'x.png',
            itemName: 'CMA',
            itemId: 68,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: -1,
            remark: '100',
            level: '202415',
            result: '1624932773714.jpg',
            itemName: 'CMA',
            itemId: 68,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          }
        ],
        projectName: null,
        projectId: null
      }
    ]
  }
]

export { mockReportData }