
// 默认报告配置用假数据
const mockReportData = [
  {
    processId: '76e98271e33446a4a8190921d8677163',
    deptCode: null,
    deptId: '03ae2cf0c24b45209587ce153bc901e1',
    deptName: '泸州新筛分中心',
    activityName: '新生儿遗传代谢病筛查-苯丙氨酸、促甲状腺素、17α羟孕酮、葡萄糖-6-磷酸脱氢酶（血斑）',
    programCode: null,
    batchNum: '2',
    responsibleDepartment: null,
    roomplanYear: '2024',
    contact: null,
    labDate: '2024-04-18',
    reportDate: '2024-05-10',
    totalScore: '100.0%',
    ownerDeptName: '四川省妇幼保健院（实验室）',
    ownerOrganName: '四川省妇幼保健院',
    overallEvaluationTableList: [
      {
        targetName: 'G6PD',
        grade: '100',
        level: '优秀',
        evaluation: '通过'
      },
      {
        targetName: 'PHE',
        grade: '100',
        level: '优秀',
        evaluation: '通过'
      },
      {
        targetName: 'TSH',
        grade: '100',
        level: '优秀',
        evaluation: '通过'
      },
      {
        targetName: '17_Α_OHP',
        grade: '100',
        level: '优秀',
        evaluation: '通过'
      }
    ],
    reportDetailList: [
      {
        itemId: '61',
        itemName: 'PHE',
        score: '100.0%',
        calculateGroupName: '丰华试剂组-PHE',
        groupLabNum: '4',
        unit: 'mg/dL',
        method: 'TSH、17_A_OHP时间分辨荧光法；PHE、G6PD荧光法',
        instrumentName: 'FH414127',
        instrumentType: 'Auto TRFIA-4',
        reagentType: '丰华组试剂',
        reagentNum: '2023082 4',
        reagent: '328',
        standard: '广州丰华',
        itemQualityResultStatisticalMethod: 1,
        roomResultList: [
          {
            roomDataLevel: '202421',
            roomResult: 4.61,
            roomX: 4.16,
            roomSd: 0.28,
            offset: '10.82',
            score: '90',
            nsd: 0.11,
            range: '2.91~5.41',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '61'
          },
          {
            roomDataLevel: '202422',
            roomResult: 11.38,
            roomX: 11.81,
            roomSd: 0.38,
            offset: '-3.64',
            score: '100',
            nsd: -0.04,
            range: '8.27~15.35',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '61'
          },
          {
            roomDataLevel: '202423',
            roomResult: 8.55,
            roomX: 8.53,
            roomSd: 0.19,
            offset: '0.23',
            score: '100',
            nsd: 0,
            range: '5.97~11.09',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '61'
          },
          {
            roomDataLevel: '202424',
            roomResult: 1.33,
            roomX: 1.19,
            roomSd: 0.09,
            offset: '11.76',
            score: '90',
            nsd: 0.12,
            range: '0.83~1.55',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '61'
          },
          {
            roomDataLevel: '202425',
            roomResult: 5.42,
            roomX: 5.88,
            roomSd: 0.35,
            offset: '-7.82',
            score: '100',
            nsd: -0.08,
            range: '4.12~7.64',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '61'
          }
        ],
        planStatisticsDtoList: [
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202421',
            conclusionResult: '阳性',
            conclusionCode: 'h',
            correctCode: 'h',
            correctResult: '阳性',
            evaluateResult: '通过',
            targetId: '61',
            itemId: '52'
          },
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202422',
            conclusionResult: '阳性',
            conclusionCode: 'h',
            correctCode: 'h',
            correctResult: '阳性',
            evaluateResult: '通过',
            targetId: '61',
            itemId: '52'
          },
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202423',
            conclusionResult: '阳性',
            conclusionCode: 'h',
            correctCode: 'h',
            correctResult: '阳性',
            evaluateResult: '通过',
            targetId: '61',
            itemId: '52'
          },
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202424',
            conclusionResult: '阴性',
            conclusionCode: 'n',
            correctCode: 'n',
            correctResult: '阴性',
            evaluateResult: '通过',
            targetId: '61',
            itemId: '52'
          },
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202425',
            conclusionResult: '阳性',
            conclusionCode: 'h',
            correctCode: 'h',
            correctResult: '阳性',
            evaluateResult: '通过',
            targetId: '61',
            itemId: '52'
          }
        ],
        describeList: null,
        dataAttachmentsList: [
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202421',
            result: null,
            itemName: 'PHE',
            itemId: 61,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202422',
            result: null,
            itemName: 'PHE',
            itemId: 61,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202423',
            result: null,
            itemName: 'PHE',
            itemId: 61,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202424',
            result: null,
            itemName: 'PHE',
            itemId: 61,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202425',
            result: null,
            itemName: 'PHE',
            itemId: 61,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          }
        ],
        projectName: 'PHE',
        projectId: 52
      },
      {
        itemId: '63',
        itemName: 'TSH',
        score: '100.0%',
        calculateGroupName: '丰华试剂组-TSH',
        groupLabNum: '4',
        unit: 'uIU/mL',
        method: 'TSH、17_A_OHP时间分辨荧光法；PHE、G6PD荧光法',
        instrumentName: 'FH414127',
        instrumentType: 'Auto TRFIA-4',
        reagentType: '丰华组试剂',
        reagentNum: '20231124',
        reagent: '359',
        standard: '广州丰华',
        itemQualityResultStatisticalMethod: 1,
        roomResultList: [
          {
            roomDataLevel: '202421',
            roomResult: 21.61,
            roomX: 20.36,
            roomSd: 1.52,
            offset: '6.14',
            score: '100',
            nsd: 0.06,
            range: '14.25~26.47',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '63'
          },
          {
            roomDataLevel: '202422',
            roomResult: 57.91,
            roomX: 57.77,
            roomSd: 5.65,
            offset: '0.24',
            score: '100',
            nsd: 0,
            range: '40.44~75.1',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '63'
          },
          {
            roomDataLevel: '202423',
            roomResult: 30.21,
            roomX: 30.79,
            roomSd: 1.04,
            offset: '-1.88',
            score: '100',
            nsd: -0.02,
            range: '21.55~40.03',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '63'
          },
          {
            roomDataLevel: '202424',
            roomResult: 42.11,
            roomX: 42.93,
            roomSd: 1.59,
            offset: '-1.91',
            score: '100',
            nsd: -0.02,
            range: '30.05~55.81',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '63'
          },
          {
            roomDataLevel: '202425',
            roomResult: 5.18,
            roomX: 4.58,
            roomSd: 0.62,
            offset: '13.1',
            score: '90',
            nsd: 0.13,
            range: '3.21~5.95',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '63'
          }
        ],
        planStatisticsDtoList: [
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202421',
            conclusionResult: '阳性',
            conclusionCode: 'h',
            correctCode: 'h',
            correctResult: '阳性',
            evaluateResult: '通过',
            targetId: '63',
            itemId: '53'
          },
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202422',
            conclusionResult: '阳性',
            conclusionCode: 'h',
            correctCode: 'h',
            correctResult: '阳性',
            evaluateResult: '通过',
            targetId: '63',
            itemId: '53'
          },
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202423',
            conclusionResult: '阳性',
            conclusionCode: 'h',
            correctCode: 'h',
            correctResult: '阳性',
            evaluateResult: '通过',
            targetId: '63',
            itemId: '53'
          },
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202424',
            conclusionResult: '阳性',
            conclusionCode: 'h',
            correctCode: 'h',
            correctResult: '阳性',
            evaluateResult: '通过',
            targetId: '63',
            itemId: '53'
          },
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202425',
            conclusionResult: '阴性',
            conclusionCode: 'n',
            correctCode: 'n',
            correctResult: '阴性',
            evaluateResult: '通过',
            targetId: '63',
            itemId: '53'
          }
        ],
        describeList: null,
        dataAttachmentsList: [
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202421',
            result: null,
            itemName: 'TSH',
            itemId: 63,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202422',
            result: null,
            itemName: 'TSH',
            itemId: 63,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202423',
            result: null,
            itemName: 'TSH',
            itemId: 63,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202424',
            result: null,
            itemName: 'TSH',
            itemId: 63,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202425',
            result: null,
            itemName: 'TSH',
            itemId: 63,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          }
        ],
        projectName: 'TSH',
        projectId: 53
      },
      {
        itemId: '64',
        itemName: '17_Α_OHP',
        score: '100.0%',
        calculateGroupName: '丰华试剂组-17-OHP',
        groupLabNum: '4',
        unit: 'nmol/L',
        method: 'TSH、17_A_OHP时间分辨荧光法；PHE、G6PD荧光法',
        instrumentName: 'FH414127',
        instrumentType: 'Auto TRFIA-4',
        reagentType: '丰华组试剂',
        reagentNum: '20231102',
        reagent: '360',
        standard: '广州丰华',
        itemQualityResultStatisticalMethod: 1,
        roomResultList: [
          {
            roomDataLevel: '202421',
            roomResult: 86.61,
            roomX: 85.95,
            roomSd: 2.38,
            offset: '0.77',
            score: '100',
            nsd: 0.01,
            range: '60.16~111.74',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '64'
          },
          {
            roomDataLevel: '202422',
            roomResult: 11.21,
            roomX: 11,
            roomSd: 0.46,
            offset: '1.91',
            score: '100',
            nsd: 0.02,
            range: '7.7~14.3',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '64'
          },
          {
            roomDataLevel: '202423',
            roomResult: 83.81,
            roomX: 82.03,
            roomSd: 2,
            offset: '2.17',
            score: '100',
            nsd: 0.02,
            range: '57.42~106.64',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '64'
          },
          {
            roomDataLevel: '202424',
            roomResult: 99.41,
            roomX: 98.12,
            roomSd: 1.56,
            offset: '1.31',
            score: '100',
            nsd: 0.01,
            range: '68.68~127.56',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '64'
          },
          {
            roomDataLevel: '202425',
            roomResult: 10.11,
            roomX: 11.74,
            roomSd: 0.94,
            offset: '-13.88',
            score: '90',
            nsd: -0.14,
            range: '8.22~15.26',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '64'
          }
        ],
        planStatisticsDtoList: [
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202421',
            conclusionResult: '阳性',
            conclusionCode: 'h',
            correctCode: 'h',
            correctResult: '阳性',
            evaluateResult: '通过',
            targetId: '64',
            itemId: '54'
          },
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202422',
            conclusionResult: '阴性',
            conclusionCode: 'n',
            correctCode: 'n',
            correctResult: '阴性',
            evaluateResult: '通过',
            targetId: '64',
            itemId: '54'
          },
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202423',
            conclusionResult: '阳性',
            conclusionCode: 'h',
            correctCode: 'h',
            correctResult: '阳性',
            evaluateResult: '通过',
            targetId: '64',
            itemId: '54'
          },
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202424',
            conclusionResult: '阳性',
            conclusionCode: 'h',
            correctCode: 'h',
            correctResult: '阳性',
            evaluateResult: '通过',
            targetId: '64',
            itemId: '54'
          },
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202425',
            conclusionResult: '阴性',
            conclusionCode: 'n',
            correctCode: 'n',
            correctResult: '阴性',
            evaluateResult: '通过',
            targetId: '64',
            itemId: '54'
          }
        ],
        describeList: null,
        dataAttachmentsList: [
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202421',
            result: null,
            itemName: '17_Α_OHP',
            itemId: 64,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202422',
            result: null,
            itemName: '17_Α_OHP',
            itemId: 64,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202423',
            result: null,
            itemName: '17_Α_OHP',
            itemId: 64,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202424',
            result: null,
            itemName: '17_Α_OHP',
            itemId: 64,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202425',
            result: null,
            itemName: '17_Α_OHP',
            itemId: 64,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          }
        ],
        projectName: '17_Α_OHP',
        projectId: 54
      },
      {
        itemId: '67',
        itemName: 'G6PD',
        score: '100.0%',
        calculateGroupName: '丰华试剂组-G6PD',
        groupLabNum: '4',
        unit: 'U/gHb',
        method: 'TSH、17_A_OHP时间分辨荧光法；PHE、G6PD荧光法',
        instrumentName: 'FH414127',
        instrumentType: 'Auto TRFIA-4',
        reagentType: '丰华组试剂',
        reagentNum: '20231204',
        reagent: '358',
        standard: '广州丰华',
        itemQualityResultStatisticalMethod: 1,
        roomResultList: [
          {
            roomDataLevel: '202421',
            roomResult: 1.08,
            roomX: 1.12,
            roomSd: 0.02,
            offset: '-3.57',
            score: '100',
            nsd: -0.04,
            range: '0.78~1.46',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '67'
          },
          {
            roomDataLevel: '202422',
            roomResult: 6.45,
            roomX: 6.3,
            roomSd: 0.21,
            offset: '2.38',
            score: '100',
            nsd: 0.02,
            range: '4.41~8.19',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '67'
          },
          {
            roomDataLevel: '202423',
            roomResult: 2.29,
            roomX: 2.29,
            roomSd: 0.11,
            offset: '0.0',
            score: '100',
            nsd: 0,
            range: '1.6~2.98',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '67'
          },
          {
            roomDataLevel: '202424',
            roomResult: 7.25,
            roomX: 7.16,
            roomSd: 0.29,
            offset: '1.26',
            score: '100',
            nsd: 0.01,
            range: '5.01~9.31',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '67'
          },
          {
            roomDataLevel: '202425',
            roomResult: 1.05,
            roomX: 1.09,
            roomSd: 0.06,
            offset: '-3.67',
            score: '100',
            nsd: -0.04,
            range: '0.76~1.42',
            evaluateResult: '通过',
            fileName: null,
            filePath: null,
            targetId: '67'
          }
        ],
        planStatisticsDtoList: [
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202421',
            conclusionResult: '阳性',
            conclusionCode: 'h',
            correctCode: 'h',
            correctResult: '阳性',
            evaluateResult: '通过',
            targetId: '67',
            itemId: '55'
          },
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202422',
            conclusionResult: '阴性',
            conclusionCode: 'n',
            correctCode: 'n',
            correctResult: '阴性',
            evaluateResult: '通过',
            targetId: '67',
            itemId: '55'
          },
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202423',
            conclusionResult: '阳性',
            conclusionCode: 'h',
            correctCode: 'h',
            correctResult: '阳性',
            evaluateResult: '通过',
            targetId: '67',
            itemId: '55'
          },
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202424',
            conclusionResult: '阴性',
            conclusionCode: 'n',
            correctCode: 'n',
            correctResult: '阴性',
            evaluateResult: '通过',
            targetId: '67',
            itemId: '55'
          },
          {
            processId: '76e98271e33446a4a8190921d8677163',
            roomDataLevel: '202425',
            conclusionResult: '阳性',
            conclusionCode: 'h',
            correctCode: 'h',
            correctResult: '阳性',
            evaluateResult: '通过',
            targetId: '67',
            itemId: '55'
          }
        ],
        describeList: null,
        dataAttachmentsList: [
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202421',
            result: null,
            itemName: 'G6PD',
            itemId: 67,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202422',
            result: null,
            itemName: 'G6PD',
            itemId: 67,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202423',
            result: null,
            itemName: 'G6PD',
            itemId: 67,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202424',
            result: null,
            itemName: 'G6PD',
            itemId: 67,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          },
          {
            readId: null,
            dataId: null,
            status: null,
            remark: null,
            level: '202425',
            result: null,
            itemName: 'G6PD',
            itemId: 67,
            expectedName: null,
            expectedValue: null,
            fileName: null,
            filePath: null
          }
        ],
        projectName: 'G6PD',
        projectId: 55
      }
    ],
    fmarkprocess1: '"8.00"',
    fmarkprocess2: '"3.40"',
    fmarkprocess3: '"30.00"',
    fmarkprocess4: null,
    fmarkprocess5: null,
    fmarkprocess6: null,
    fmarkprocess7: null,
    fmarkprocess8: null,
    fmarkprocess9: null,
    fmarkprocess10: null,
    fmarkplan1: '"SCFY-E-202402"',
    fmarkplan2: null,
    fmarkplan3: null,
    fmarkplan4: null,
    fmarkplan5: null,
    fmarkplan6: null,
    fmarkplan7: null,
    fmarkplan8: null,
    fmarkplan9: null,
    fmarkplan10: null
  }
]

export { mockReportData }